feat: test suite
Byzanteam/jet-queue-plugin-js pull request #11
Opened 2024-02-20 09:03 UTC by danewalters

2024-02-21 03:34 UTC, fahchen requested changes
到 time-slot-reservation 那边提一个应用了 JetQueueTesting 的 draft PR，看下如何使用，同时在 README 中增加一下 `Testings` 的文档

2024-02-21 03:34 UTC, fahchen commented on src/testing.ts
> +  }
给它们写一下测试呢

2024-02-21 03:34 UTC, fahchen commented on src/testing.ts
> +// deno-lint-ignore-file
修一下 deno-lint 的错误
```suggestion
```

2024-02-21 03:34 UTC, fahchen commented on src/testing.ts
> +export class JetQueueTest extends JetQueueBase {
```suggestion
export class JetQueueTesting extends JetQueueBase {
```

2024-02-21 05:26 UTC, CptBreeza commented on src/testing.ts
> +  async enqueue<
像这样没有用 await 的函数就不要加 async 了

2024-02-21 07:28 UTC, fahchen commented on src/testing.ts
> +  }
这里面可以用 assert，外面不写 assert(assertEnqueue) 了

2024-02-21 07:28 UTC, fahchen commented on src/testing_test.ts
> +    assertEquals(jetQueue.getJobs().length, 0);
getJobs 是不是没有被测试过？

2024-02-27 08:05 UTC, CptBreeza commented on src/queue_test_helper.ts
> +  }
这个不太对：
1. 应该直接返回 queue.enqueue 就可以了，不需要再包一个 enqueue 函数出来
2. 没有返回 listen 函数

2024-02-27 08:36 UTC, CptBreeza commented on src/queue_test_helper.ts
> +}
这里不要拆成 2 个 use，外面用的时候会这样写：
```typescript
const { enqueue, listen } = useQueue("timing");
```

2024-02-27 09:41 UTC, fahchen requested changes

2024-02-27 09:41 UTC, fahchen commented on src/queue_test_helper.ts
useQueue 不应该出现在 test_helper 中哦

2024-02-27 09:41 UTC, fahchen commented on src/testing.ts
> +  }
这个挪到对应的使用的地方变成一个 private function 就可以了

2024-02-29 06:44 UTC, CptBreeza approved these changes

2024-02-29 07:29 UTC, fahchen requested changes

2024-02-29 07:29 UTC, fahchen commented on src/types.ts
> +export abstract class JetQueueBase {
这个抽象类我感觉可以不要了

2024-02-29 07:50 UTC, CptBreeza approved these changes

2024-02-29 07:52 UTC, fahchen commented on src/types.ts
> +) => Promise<void>;
这个不要手写，通过 JetQueue 推出来

2024-02-29 07:52 UTC, fahchen commented on src/use-queue.ts
> +    const fn = functions[functionName] as unknown as (
这个应该没必要才对

```suggestion
    const fn = functions[functionName] as (
```

2024-02-29 07:58 UTC, fahchen commented on src/types.ts
> +export type ListenFunction = JetQueue["listen"];
这个没必要导出，直接在用的地方推导就行了

2024-02-29 08:07 UTC, fahchen approved these changes

2024-02-29 08:29 UTC, merged