feat: jet queue cancel
Byzanteam/jet-queue-plugin-js pull request #16
Opened 2024-03-06 08:04 UTC by danewalters

2024-03-06 12:02 UTC, fahchen requested changes

2024-03-06 12:02 UTC, fahchen commented on src/queue.ts
> +  }
和 post 的代码重复度太高了

2024-03-06 12:02 UTC, fahchen commented on src/testing.ts
> +
这个东西测试下

2024-03-06 12:04 UTC, fahchen requested changes

2024-03-06 12:04 UTC, fahchen commented on src/queue.ts
> +  }
如果 job 找不到是不会报错的

2024-03-07 08:51 UTC, fahchen approved these changes

2024-03-08 04:09 UTC, CptBreeza approved these changes

2024-03-08 04:10 UTC, merged