test: replace test
Byzanteam/jet-queue-plugin-js pull request #25
Opened 2024-06-25 08:21 UTC by danewalters

2024-06-25 08:54 UTC, fahchen requested changes

2024-06-25 08:54 UTC, fahchen commented on src/testing.ts
> +        is_conflict: false,
```suggestion
        is_conflict: true,
```

2024-06-25 08:54 UTC, fahchen commented on src/testing.ts
> +      matchUnique(args, job.args, options?.unique)
```suggestion
      isConflict(args, job.args, options?.unique)
```

2024-06-25 08:54 UTC, fahchen commented on src/testing.ts
> +  return unique.keys.every((key) => args[key] === jobArgs[key]);
判定冲突的时候除了 args 还有 meta

2024-06-25 08:54 UTC, fahchen commented on src/testing.ts
> +    // NOTE: 这里目前只能支持 args 冲突检测
如果传了现在没有实现的参数，给一下报错，避免测试的时候忽略到这种错误

2024-06-25 08:54 UTC, fahchen commented on src/testing.ts
> +  const replaceOptions = options.replace! as ReplacementOptions;
如果 replace 没有传值，就不做任何处理

2024-06-25 08:54 UTC, fahchen commented on src/testing.ts
> +  if (Object.keys(replaceOptions).includes("all")) {
```suggestion
  if (Object.hasOwn(replaceOptions, "all")) {
```

2024-06-25 08:54 UTC, fahchen commented on src/testing.ts
> +  if (Object.keys(replaceOptions).includes("all")) {
这里不做特殊处理了，将 all 展开成所有状态，然后处理吧

2024-06-25 08:54 UTC, fahchen commented on src/testing_test.ts
> +    assert(foundJobThree?.[2]?.scheduledAt, "ScheduledAt should be found");
```suggestion
    assert(foundJobThree?.[2]?.scheduledAt, "ScheduledAt should be set");
```

2024-06-25 08:54 UTC, fahchen commented on src/testing_test.ts
> +    assertEquals(foundJobTwo?.[2]?.priority, 2, "Priority should be 2");
这里断言 foundJobTwo 和 foundJob 是同一个 jobId，isConflict 为 true

2024-06-25 08:54 UTC, fahchen commented on src/testing_test.ts
> +    const jobArgsTwo = { id: "projectIdTwo" };
这个可以不用作为一个变量，在用的地方写 literal 就好了，这个 two 和下面的 foundJobTwo 不是对应关系，现在这些名字取得有点混淆

2024-06-25 09:46 UTC, danewalters commented on src/testing.ts
> +  const replaceOptions = options.replace! as ReplacementOptions;
上面校验了 replace 有值才会进入到这里

2024-06-25 10:02 UTC, fahchen commented on src/testing.ts
> +  const replaceOptions = options.replace! as ReplacementOptions;
如果冲突了，但是没有给 replace 也是成立的，你上面的判断不太对

2024-06-25 10:03 UTC, fahchen requested changes
问题没改完

2024-06-25 11:23 UTC, fahchen requested changes

2024-06-25 11:23 UTC, fahchen commented on src/testing.ts
> +    }
replace option 没有指定的时候，检测到冲突时，is_conflict 也要为 true

2024-06-25 11:23 UTC, fahchen commented on src/testing.ts
> +        existingOptions?.meta,
参数合并一下吧

2024-06-25 11:23 UTC, fahchen commented on src/testing.ts
> +    // NOTE: 测试环境目前不支持区分状态的替换
这个为啥不做上呢？

2024-06-25 11:23 UTC, fahchen commented on src/testing_test.ts
> +  it("should handle job priority replacement correctly", async () => {
测试用例拆下一点

2024-06-25 12:57 UTC, danewalters commented on src/testing.ts
> +    // NOTE: 测试环境目前不支持区分状态的替换
我们现在插入队列在测试环境中，无法有效的模拟状态。
根据测试范围我们这边只要测试到到能不能插入正确的数据就可以了，关于队列的 replace 这边应该是不用做的，毕竟这边的 sdk 也是不具备这个功能的，我们需要保证的是传入的数据正确并且有效。执行方面的测试应该是 queue 插件那边做的

2024-06-26 01:02 UTC, fahchen commented on src/testing_test.ts
> +  it("should handle job priority replacement correctly", async () => {
测试用例拆小成多个，让每个用例测试的内容单一

2024-06-26 01:04 UTC, fahchen commented on src/testing.ts
> +    // NOTE: 测试环境目前不支持区分状态的替换
你这么说的话，感觉我们可以不实现 replace，我们直接看插入的参数对不对就好了。可以考虑不实现 replace 了

2024-07-01 03:16 UTC, closed without merging