feat: multi queue subscriber
Byzanteam/jet-queue-plugin-js pull request #26
Opened 2024-07-09 08:58 UTC by danewalters

2024-07-09 09:53 UTC, fahchen requested changes

2024-07-09 09:53 UTC, fahchen commented on src/queue.ts
> +  }
```suggestion
  public get queue(): string {
    return this.queue;
  }
```

2024-07-09 09:53 UTC, fahchen commented on src/types.ts
> +export interface Queue<T extends Record<string, unknown>> {
这个范型参数没地方用到

2024-07-09 09:53 UTC, fahchen commented on src/multi_queue_subscriber.ts
> +  }
单独做一个不依赖 JetQueue 的 class 出来吧
这里的 batchSize 和 bufferSize 重新设计一下
1. 每个 queue 可以指定 bufferSize
2. 一个 subscriber 可以指定一个 batchSize

2024-07-09 10:50 UTC, fahchen requested changes
参数调整一下
1. queue数组：name 和 bufferSize
2. batchSize
3. instanceName

2024-07-09 10:50 UTC, fahchen commented on src/multi_queue_subscriber.ts
> +  public async listenToMultipleQueues(
```suggestion
  public async listen(
```

2024-07-09 13:39 UTC, fahchen reviewed
其他没问题了

2024-07-09 13:39 UTC, fahchen commented on src/multi_queue_subscriber.ts
> +export class MultiQueueSubscriber<T extends Record<string, unknown>> {
就叫 queue 吧，同时支持单个和多个 queue 订阅

```suggestion
export class QueueSubscriber<T extends Record<string, unknown>> {
```

2024-07-10 03:26 UTC, fahchen reviewed
创建一个项目测试一下是否正常工作

2024-07-10 06:55 UTC, danewalters commented
> 创建一个项目测试一下是否正常工作

测试成功了， 可以正常运行
https://nightly.jet.apps.jet.work/breeze/queue_listen_test/development/main

2024-07-10 10:02 UTC, fahchen commented
贴一下测试的日志

2024-07-10 10:08 UTC, danewalters commented
> 贴一下测试的日志

### 两个队列的任务入队
<img width="303" alt="Screenshot 2024-07-10 at 18 05 41" src="https://github.com/Byzanteam/jet-queue-plugin-js/assets/91400014/7ddfdefe-c59e-45fa-af69-ee6fb1c57849">

### 使用多项目订阅
<img width="435" alt="Screenshot 2024-07-10 at 18 05 57" src="https://github.com/Byzanteam/jet-queue-plugin-js/assets/91400014/9e7db613-a0e5-4227-9c1e-d4e2859185e5">

### 队列消费，将信息格式化打印
<img width="757" alt="Screenshot 2024-07-10 at 18 05 13" src="https://github.com/Byzanteam/jet-queue-plugin-js/assets/91400014/a97af775-07f0-4092-8731-f82bb3719c7d">

2024-07-11 02:31 UTC, merged