draft commit
Byzanteam/jet-queue-plugin-js pull request #32
Opened 2024-07-23 08:11 UTC by danewalters

2024-07-23 10:49 UTC, fahchen requested changes

2024-07-23 10:49 UTC, fahchen commented on dev_deps.ts
> +export * from "https://deno.land/std@0.208.0/testing/mock.ts";
```suggestion
export * from "https://deno.land/std@0.218.0/testing/mock.ts";
```

2024-07-23 10:49 UTC, fahchen commented on src/testing.ts
> +} from "../dev_deps.ts";
这些都通过参数传进来吧，这这里面的类型可以写得宽松点，用 any 也没啥大问题

2024-07-23 10:49 UTC, fahchen commented on src/use-queue.ts
按上次讨论的结果把 useQueue 删除吧

2024-07-23 10:51 UTC, danewalters commented on src/use-queue.ts
其实留着也还可以的，不然的话会优先加载这个代码。会直接报错
```ts
private pluginInstance: BreezeRuntime.Plugin;
```

2024-07-23 12:34 UTC, fahchen commented on src/use-queue.ts
想想怎么重新组织下代码，让它不报错吧

2024-07-24 02:52 UTC, fahchen approved these changes

2024-07-24 03:33 UTC, fahchen approved these changes

2024-07-24 03:37 UTC, merged